[module]
name = "convert"
version = "0.1.0"
description = "Unit conversion utilities for mass and temperature. This is just a demo"
authors = [
    { name = "Joshua Marie", email = "joshua.marie.k@gmail.com" }
]
license = "Unknown"
r_version = "4.0.0"
 
[package_deps]
 
[module_deps]
 
[test]
framework = "testthat"
dir = "tests"
