[package]
name = "carrier-cli"
version.workspace = true
edition.workspace = true
description = "A bundler and package manager for box modules"
default-run = "carrier"

[lib]
name = "carrier_cli"
path = "src/lib.rs"

[[bin]]
name = "carrier"
path = "src/bin/carrier.rs"

[[bin]]
name = "box-crr"
path = "src/bin/crr.rs"

[dependencies]
carrier-core = { path = "../carrier-core", features = ["network"] }
carrier-native = { path = "../carrier-native" }
anyhow.workspace = true
clap.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
